@startuml hello

'-Style----------------------------------------------------------------------------------------------------------------

autonumber

skinparam DefaultTextAlignment center

skinparam BackgroundColor #fafdff

skinparam sequence {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION

    ActorBackgroundColor APPLICATION
    ActorBorderColor DodgerBlue

    BackgroundColor #FFFFFF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue

    ParticipantBackgroundColor DodgerBlue
    ParticipantFontColor #FFFFFF
    ParticipantBorderColor DodgerBlue

    GroupBorderColor #082642
    GroupBackgroundColor APPLICATION
}

skinparam note {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION

    ActorBackgroundColor APPLICATION
    ActorBorderColor DodgerBlue

    BackgroundColor #FFFFFF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue

    ParticipantBackgroundColor DodgerBlue
    ParticipantFontColor #FFFFFF
    ParticipantBorderColor DodgerBlue

    GroupBorderColor #082642
    GroupBackgroundColor APPLICATION
}

'-Title----------------------------------------------------------------------------------------------------------------

title UC04: Criar nova Entrega
'-Actors/Participants--------------------------------------------------------------------------------------------------

actor "<b>Gestor de Armazém" as A
participant "<b>:EntregaController" as AC
participant "<b>:EntregaService" as ASR
participant "<b>entrega\n<b>:Entrega" as ARM
participant "<b>entregaDTO\n<b>:EntregaDTO" as AD
participant "<b>:IEntregaRepository" as AR

'-Associations---------------------------------------------------------------------------------------------------------

activate A

A -> AC: HTTP request (post)
activate AC

AC -> ASR: AddAsync(dto)
activate ASR

create ARM
ASR -> ARM: Entrega(dto.id, dto.idLoja, dto.tempoCarga,\ndto.tempoDescarga, dto.data, dto.peso)

ASR -> AR: AddAsync(entrega)

create AD
ASR -> AD: EntregaDTO(entrega.id, entrega.idLoja, entrega.tempoCarga,\nentrega.tempoDescarga, entrega.data, entrega.peso)

ASR -> AC: entregaDTO

AC -> A: Cria nova Entrega e informa o utilizador do sucesso da operaçao

'----------------------------------------------------------------------------------------------------------------------

@enduml