@startuml hello

'-Style----------------------------------------------------------------------------------------------------------------

autonumber

skinparam DefaultTextAlignment center

skinparam BackgroundColor #fafdff

skinparam sequence {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION

    ActorBackgroundColor APPLICATION
    ActorBorderColor DodgerBlue

    BackgroundColor #FFFFFF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue

    ParticipantBackgroundColor DodgerBlue
    ParticipantFontColor #FFFFFF
    ParticipantBorderColor DodgerBlue

    GroupBorderColor #082642
    GroupBackgroundColor APPLICATION
}

skinparam note {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION

    ActorBackgroundColor APPLICATION
    ActorBorderColor DodgerBlue

    BackgroundColor #FFFFFF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue

    ParticipantBackgroundColor DodgerBlue
    ParticipantFontColor #FFFFFF
    ParticipantBorderColor DodgerBlue

    GroupBorderColor #082642
    GroupBackgroundColor APPLICATION
}

'-Title----------------------------------------------------------------------------------------------------------------

title US29: Como gestor de logística pretendo listar as viagens por página

'-Actors/Participants--------------------------------------------------------------------------------------------------

actor "<b>Gestor de Logística" as A
participant "<b>:SPA" as SPA
participant "<b>:ML" as M

'-Associations---------------------------------------------------------------------------------------------------------

activate A
activate M
activate SPA

A -> SPA: Pede para listar as Viagens
SPA -> M: HTTP request (get)
M -> M: Responde ao request (Retorna as viagens \n da pagina atual da base de dados \n / Informa de falha no request)
M -> SPA: Viagens da pagina atual
SPA -> A: Mostra as Viagens e informa o utilizador do sucesso da operaçao

'----------------------------------------------------------------------------------------------------------------------

@enduml