@startuml hello

'-Style----------------------------------------------------------------------------------------------------------------

autonumber

skinparam DefaultTextAlignment center

skinparam BackgroundColor #fafdff

skinparam sequence {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION

    ActorBackgroundColor APPLICATION
    ActorBorderColor DodgerBlue

    BackgroundColor #FFFFFF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue

    ParticipantBackgroundColor DodgerBlue
    ParticipantFontColor #FFFFFF
    ParticipantBorderColor DodgerBlue

    GroupBorderColor #082642
    GroupBackgroundColor APPLICATION
}

skinparam note {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION

    ActorBackgroundColor APPLICATION
    ActorBorderColor DodgerBlue

    BackgroundColor #FFFFFF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue

    ParticipantBackgroundColor DodgerBlue
    ParticipantFontColor #FFFFFF
    ParticipantBorderColor DodgerBlue

    GroupBorderColor #082642
    GroupBackgroundColor APPLICATION
}

'-Title----------------------------------------------------------------------------------------------------------------

title US31: Como gestor de armazéns pretendo ordenar Entregas

'-Actors/Participants--------------------------------------------------------------------------------------------------

actor "<b>Gestor de Armazens" as A
participant "<b>:EntregaUI" as CU
participant "<b>:EntregaComponent" as CC
participant "<b>:EntregaService" as CS
participant "<b>:BackEndGestaoDeArmazens" as AL


'-Associations---------------------------------------------------------------------------------------------------------

activate A

A -> CU: Abre a página relativa a entregas e seleciona a opção \n Ordenar pela data/por armazém
activate CU
CU -> CC: getEntregasOrderedByData()/getEntregasOrderedByArmazem()
activate CC
CC -> CS : getEntregasOrderedByData()/getEntregasOrderedByArmazem()
activate CS
deactivate CC
CS -> AL : getEntregasOrderedByData()/getEntregasOrderedByArmazem()

ref over AL
 ./MGA/US31_Ordenar_Entregas.puml
end ref
activate AL
deactivate CS
AL -> CS : listaEntregas
deactivate AL
activate CS
CS -> CC : listaEntregas
deactivate CS
activate CC
CC -> CU : listaEntregas
deactivate CC
CU -> A: Mostra as entregas, de acordo com o filtro, presentes no sistema ao utilizador

deactivate CU

'----------------------------------------------------------------------------------------------------------------------

@enduml